export const INITIALIZE = 'INITIALIZE';

export const UPDATE_CORE_INFO = 'UPDATE_CORE_INFO';
export const UPDATE_THEME = 'UPDATE_THEME';

export const SHOW_CONNECTIONS = 'SHOW_CONNECTIONS';
export const HIDE_CONNECTIONS = 'HIDE_CONNECTIONS';

export const UPDATE_INPUT = 'UPDATE_INPUT';

export const LOAD_INVOICE_DRAFTS = 'LOAD_INVOICE_DRAFTS';
export const ADD_NEW_INVOICE_DRAFT = 'ADD_NEW_INVOICE_DRAFT';
export const UPDATE_INVOICE_DRAFT = 'UPDATE_INVOICE_DRAFT';
export const DELETE_INVOICE_DRAFT = 'DELETE_INVOICE_DRAFT';
export const SET_INVOICES = 'SET_INVOICES';
export const SET_INVOICE_REFERENCE_QUERY = 'SET_INVOICE_REFERENCE_QUERY';
export const SET_INVOICE_STATUS_FILTER = 'SET_INVOICE_STATUS_FILTER';
export const SET_INVOICE_TIME_FILTER = 'SET_INVOICE_TIME_FILTER';

export const SET_POP_UP = 'SET_POP_UP';
export const CLOSE_POP_UP = 'CLOSE_POP_UP';

export const SET_USER_ACCOUNTS = 'SET_USER_ACCOUNTS';
