export const INITIALIZE = 'INITIALIZE';
export const SHOW_VERSION = 'SHOW_VERSION';
export const HIDE_VERSION = 'HIDE_VERSION';
export const UPDATE_CORE_INFO = 'UPDATE_CORE_INFO';
export const UPDATE_THEME = 'UPDATE_THEME';
