export const INITIALIZE = 'INITIALIZE';

export const UPDATE_CORE_INFO = 'UPDATE_CORE_INFO';
export const UPDATE_THEME = 'UPDATE_THEME';

export const SHOW_CONNECTIONS = 'SHOW_CONNECTIONS';
export const HIDE_CONNECTIONS = 'HIDE_CONNECTIONS';

export const UPDATE_INPUT = 'UPDATE_INPUT';
